// Text constants for the application
export const TEXT = {
  // General
  dashboard: 'Dashboard',
  licenses: 'Licenses',
  expenses: 'Expenses',
  income: 'Income',
  settings: 'Settings',
  about: 'About',
  version: 'Version',
  applyChanges: 'Apply Changes',
  
  // Dashboard
  totalLicenses: 'Total Licenses',
  licenseCosts: 'License Costs',
  totalExpenses: 'Total Expenses',
  totalIncome: 'Total Income',
  activeReminders: 'Active Reminders',
  expensesByCategory: 'Expenses by Category',
  financialOverview: 'Financial Overview',
  upcomingPayments: 'Upcoming Payments',
  noUpcomingPayments: 'No upcoming payments',
  noExpensesYet: 'No expenses yet',
  quickAccess: 'Quick Access',
  manageYourExpenses: 'Manage Your Expenses',
  trackYourLicenses: 'Track Your Licenses',
  customizeYourExperience: 'Customize Your Experience',
  viewAll: 'View All',
  configure: 'Configure',
  
  // Licenses
  addLicense: 'Add License',
  editLicense: 'Edit License',
  licenseName: 'License Name',
  enterLicenseName: 'Enter license name',
  startDate: 'Start Date',
  renewalFrequency: 'Renewal Frequency',
  renewalCost: 'Renewal Cost',
  nextDueDate: 'Next Due Date',
  notes: 'Notes',
  optionalNotes: 'Optional notes',
  cancel: 'Cancel',
  saveLicense: 'Save License',
  updateLicense: 'Update License',
  noLicensesFound: 'No licenses found',
  confirmDeleteLicense: 'Are you sure you want to delete this license?',
  startDateRequired: 'Start date is required',
  autoCalculated: 'Auto-calculated based on start date and frequency',
  custom: 'Custom',
  
  // Expenses
  addExpense: 'Add Expense',
  editExpense: 'Edit Expense',
  expenseName: 'Expense Name',
  enterExpenseName: 'Enter expense name',
  category: 'Category',
  selectCategory: 'Select category',
  software: 'Software',
  hardware: 'Hardware',
  services: 'Services',
  utilities: 'Utilities',
  rent: 'Rent',
  studioRent: 'Studio Rent',
  officeRent: 'Office Rent',
  broadcastingEquipment: 'Broadcasting Equipment',
  broadcastingLicenses: 'Broadcasting Licenses',
  musicLicensing: 'Music Licensing',
  talentFees: 'Talent Fees',
  productionSoftware: 'Production Software',
  marketing: 'Marketing & Promotion',
  salaries: 'Salaries',
  other: 'Other',
  frequency: 'Frequency',
  amount: 'Amount',
  dueDate: 'Due Date',
  saveExpense: 'Save Expense',
  updateExpense: 'Update Expense',
  noExpensesFound: 'No expenses found',
  confirmDeleteExpense: 'Are you sure you want to delete this expense?',
  
  // Income
  addIncome: 'Add Income',
  editIncome: 'Edit Income',
  incomeName: 'Income Name',
  enterIncomeName: 'Enter income name',
  incomeCategory: 'Category',
  salary: 'Salary',
  freelance: 'Freelance',
  investments: 'Investments',
  rental: 'Rental',
  royalties: 'Royalties',
  business: 'Business',
  incomeAmount: 'Amount',
  incomeFrequency: 'Frequency',
  // Time periods - also used in Settings
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  quarterly: 'Quarterly',
  yearly: 'Yearly',
  oneTime: 'One-time',
  nextReceiptDate: 'Next Receipt Date',
  nextReceipt: 'Next Receipt',
  saveIncome: 'Save Income',
  updateIncome: 'Update Income',
  noIncomeFound: 'No income found',
  confirmDeleteIncome: 'Are you sure you want to delete this income?',
  
  // Settings
  appearance: 'Appearance',
  darkMode: 'Dark Mode',
  darkModeDescription: 'Use dark theme for the application',
  language: 'Language',
  region: 'Region',
  currentRegion: 'Current Region',
  currency: 'Currency',
  notifications: 'Notifications',
  enableNotifications: 'Enable Notifications',
  notificationsDescription: 'Receive notifications for upcoming payments',
  emailNotifications: 'Email Notifications',
  emailNotificationsDescription: 'Receive notifications via email',
  emailAddress: 'Email Address',
  account: 'Account',
  profile: 'Profile',
  name: 'Name',
  yourName: 'Your Name',
  company: 'Company',
  yourCompany: 'Your Company',
  security: 'Security',
  changePassword: 'Change Password',
  dataManagement: 'Data Management',
  backup: 'Backup',
  autoBackup: 'Auto Backup',
  autoBackupDescription: 'Automatically backup your data',
  backupFrequency: 'Backup Frequency',
  exportImport: 'Export / Import',
  exportFormat: 'Export Format',
  exportData: 'Export Data',
  importData: 'Import Data',
  resetData: 'Reset Data',
  confirmResetData: 'Are you sure you want to reset all data? This action cannot be undone.',
  
  // Status
  overdue: 'Overdue',
  soon: 'Soon',
  upcoming: 'Upcoming',
  active: 'Active',
  dueInDays: (days: number) => `Due in ${days} days`,
  
  // Actions
  view: 'View',
  viewDetails: 'View Details',
  edit: 'Edit',
  delete: 'Delete',
  renew: 'Renew',
  processPayment: 'Process Payment',
  actions: 'Actions',
  save: 'Save',
  update: 'Update',
  
  // Validation
  fieldRequired: 'This field is required',
  mustBePositive: 'Value must be greater than zero',
  nameRequired: 'Name is required',
  categoryRequired: 'Category is required',
  validAmountRequired: 'Amount must be greater than zero',
  dueDateRequired: 'Due date is required',
  
  // Filters
  filters: 'Filters',
  searchLicenses: 'Search licenses...',
  searchExpenses: 'Search expenses...',
  searchIncome: 'Search income...',
  filtersComingSoon: 'Advanced filters coming soon',
  
  // Expense Categories
  housing: 'Housing',
  transportation: 'Transportation',
  food: 'Food',
  insurance: 'Insurance',
  healthcare: 'Healthcare',
  entertainment: 'Entertainment',
  subscriptions: 'Subscriptions',
  
  // Misc
  nextRenewal: 'Next Renewal',
  cost: 'Cost',
  noLicenses: 'No licenses found',
  noExpenses: 'No expenses found',
  exportFunctionalityComingSoon: 'Export functionality coming soon',
  importFunctionalityComingSoon: 'Import functionality coming soon',
  resetFunctionalityComingSoon: 'Reset functionality coming soon'
};
